/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zodiacswing;

/**
 *
 * @author Phantom
 */
public class FrmZoodiac extends javax.swing.JFrame {

    /**
     * Creates new form FrmZoodiac
     */
    public FrmZoodiac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBulan = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtZodiacType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tanggal:");

        jLabel2.setText("Bulan:");

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.setText("Zodiac");

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42)
                        .addComponent(txtZodiacType, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtZodiacType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        int tl, bl;
        tl = Integer.parseInt(txtTanggal.getText());
        bl = Integer.parseInt(txtBulan.getText());
        if ((tl >= 21 && bl == 3) || (tl <= 20 && bl == 4)) {

            txtZodiacType.setText("ARIES (21 Maret – 20 April)");
            txtDesc.setText("Sifat Umum : suka menonjolkan diri, senang beraktifitas, menyukai kepemimpinan.");

        } else if ((tl >= 21 && bl == 4) || (tl <= 20 && bl == 5)) {

            txtZodiacType.setText("TAURUS (21 April – Mei 20)");
            txtDesc.setText("Sifat Umum : suka hak milik dan tanah, menyukai kesenangan fisik");

        } else if ((tl >= 21 && bl == 5) || (tl <= 20 && bl == 6)) {

            txtZodiacType.setText("GEMINI (21 Mei - 20 Jun)");
            txtDesc.setText("Sifat Umum : menjadi penjual jasa atau ide, senang komunikasi dan masalah kesusastraan.");

        } else if ((tl >= 21 && bl == 6) || (tl <= 22 && bl == 7)) {

            txtZodiacType.setText("CANCER (21 Jun - 22 Jul)");
            txtDesc.setText("Sifat Umum : sangat peduli dalam urusan rumah dan keluarga, senang mengumpulkan benda berharga, sentimentil.");

        } else if ((tl >= 23 && bl == 7) || (tl <= 22 && bl == 8)) {

            txtZodiacType.setText("LEO (23 Jul - 22 Aug)");
            txtDesc.setText("Sifat Umum : suka mengatur dan memerintah, menyukai media dan usaha kreatif, mengorganisir yang lain.");

        } else if ((tl >= 23 && bl == 8) || (tl <= 22 && bl == 9)) {

            txtZodiacType.setText("VIRGO (23 Aug - 22 Sep)");
            txtDesc.setText("Sifat Umum : bekerja cepat dan tepat, sehat dan higienis, suka menganalisa yang lain");

        } else if ((tl >= 23 && bl == 9) || (tl <= 22 && bl == 10)) {

            txtZodiacType.setText("LIBRA (23 Sep - 22 Oct)");
            txtDesc.setText("Sifat Umum : menyenangi ide estetika, dalam seni dan lingkungan kerja yang berorientasi kemasyarakatan, adil pada siapa saja");
        } else if ((tl >= 23 && bl == 10) || (tl <= 22 && bl == 11)) {

            txtZodiacType.setText("SCORPIO (23 Oct - 22 Nov)");
            txtDesc.setText("Sifat Umum : penuh misteri atau rahasia, menyukai problema dan riset");
        } else if ((tl >= 23 && bl == 11) || (tl <= 21 && bl == 12)) {

            txtZodiacType.setText("SAGITARIUS (23 Nov - 21 Dec)");
            txtDesc.setText("Sifat Umum : pengembara, mengejar filsafat, menyukai penelitian");
        } else if ((tl >= 22 && bl == 12) || (tl <= 19 && bl == 1)) {

            txtZodiacType.setText("CAPRICORN (22 Dec - 19 Jan)");
            txtDesc.setText("Sifat Umum : mengejar keuntungan bisnis (fiansial) dan status social");
        } else if ((tl >= 20 && bl == 1) || (tl <= 20 && bl == 2)) {

            txtZodiacType.setText("AQUARIUS (20 Jan - 19 Feb)");
            txtDesc.setText("Sifat Umum : mengejar segi kemanusiaan dan pengetahuan, menyukai aktifitas kelompok");
        } else if ((tl >= 20 && bl == 2) || (tl <= 20 && bl == 3)) {

            txtZodiacType.setText("PISCES (20 Feb - 20 Mar)");
            txtDesc.setText("Sifat Umum : menyukai hal-hal spiritual, kesenian dan lautan.");
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmZoodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmZoodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmZoodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmZoodiac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmZoodiac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBulan;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtZodiacType;
    // End of variables declaration//GEN-END:variables
}
